### ISSUE TITLE
It would be nice to write a simple test case for controller

### ISSUE THREAD

**Issue by drdev** [maestrooo/zend-skeleton-light#2]

**Comment by bakura10** [comment]
What do you want to right ? There is nothing in the controller :(.

**Comment by drdev** [comment]
There's the controller itself, an action. You can test if the action can be dispatched and it returns `ViewModel`.

For me it's primarily the reference (quickstart?) how to start testing your app.

**Comment by bakura10** [comment]
Ok. I'll try to add this. Don't hesitate to do it and make a PR, I have lot of work to do =).

**Comment by bakura10** [comment]
Hi @drdev ,

The Skeleton now contains a very simple unit test ;-).
